### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by ileiol** [Dave2ooo/oebb-monitor#1]
Hi @Dave2ooo, 

Thanks for your work. I am currently looking for a way to display a " in x minuten fährt die nächste Bim" monitor.
I am trying to install your custom component but i have a problem with the install. 
After the step "npm install" an error is occurring. I don't have any experience with coding. Saying, so I don't know what the error means. Do you know a solution? 

![Install_Problem](https://user-images.githubusercontent.com/124794516/224949622-6eccf4be-1933-442c-a346-1b842e03387d.PNG)

**Comment by Dave2ooo** [comment]
Hi, thanks for the question!
I get the same messages when installing npm. I don't understand them either but it shouldn't be a problem.
Try step 4 from the installation process (run "node cors-server.js"). If you get the message "Running CORS Anywhere on 0.0.0.0:8080" you should be good to continue the installation process.

I will update the readme so that nobody will get confused by this in the future.

Please let me know if it works or if you have troubles somewhere else.

**Comment by ileiol** [comment]
@Dave2ooo 
thanks for the reply and the explanation. I continued with the install and  got a problem with the "website card" from Love Lace. 
I changed the Home Assistant Server and I cleared my browser cache with the add on you suggested. 
Despite, I got the following error: 


![Problem install](https://user-images.githubusercontent.com/124794516/225030982-c8c7a6ea-e10e-4551-ae6c-596b3fc68c7c.PNG)

**Comment by Dave2ooo** [comment]
@ileiol
So far so good.
The webpage is working but cannot fetch the data from Scotty.
There are two reasons for this I can think of right now.

1. Make sure that the CORS server is running in the terminal.
![image](https://user-images.githubusercontent.com/71500391/225040634-d22defa0-8ca9-4f29-a535-3e1e42f04201.png)

2. Check that you wrote the IP address of your Homeassistant into the **script.js** file. (Step 5 of the Installation process)
![image](https://user-images.githubusercontent.com/71500391/225042266-18fd7d98-830f-4c5b-ae7e-ec8bc49f666c.png)
You can look up its IP address by accessing your router settings.
If you don't know how to do that: https://www.pcmag.com/how-to/how-to-access-your-wi-fi-routers-settings

After editing the **script.js** file you have to clear your browsers cache.

Could you let me know if it works or if you missed one of those steps of the installation? If you missed it I would update the according section of the guide to try to make it harder to miss.

**Comment by Dave2ooo** [comment]
@ileiol 
Did you manage to resolve the problem?

**Comment by ileiol** [comment]
Thanks for the help. I have a running öbb time table now.
Thanks a lot! :)

Dave2ooo ***@***.***> schrieb am Do., 27. Apr. 2023, 16:54:
