### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by nightfever77** [Dave2ooo/oebb-monitor#2]
HA IP is set correctly and CORS running but getting the error though. Anything else to verify?

station id: 1231201

![image](https://github.com/Dave2ooo/oebb-monitor/assets/73058571/cd5bc431-4287-44f5-83a4-c0ccd1d6b67a)

![image](https://github.com/Dave2ooo/oebb-monitor/assets/73058571/8de3a14a-f42d-4a7b-a38b-916c56812e07)

![image](https://github.com/Dave2ooo/oebb-monitor/assets/73058571/96b9e239-b500-4f2e-b5ad-af75d0b80e92)

**Comment by Dave2ooo** [comment]
It looks like you did everything correctly.

Try to clear your browsers cache as described in the README [Editing files](https://github.com/Dave2ooo/oebb-monitor?tab=readme-ov-file#34-editing-files)
Sometimes the browser won't update the source of the webpage card. So the webpage will try to acces the IP address that was written as default.

Please report back when you tried it.

**Comment by nightfever77** [comment]
Tried, also tried with a browser that has not seen HA before, still the same error.

Actually I access HA via https and my own domain name. I was thinking that there might be a context. But also tried locally via http and local IP.

**Comment by tombrex** [comment]
Hey, as far as I see from the script, this can only happen when the cors ip is not set correctly or the cors server is not reachable. To help you, I need to fully understand how your setup looks like. Some questions from my side:

1. Is the cors server running on your home assistant machine?
2. Are you accessing your home assistant only from your local network? If not, does it work locally?

Can you also open the browser console and make a screenshot of the error?

**Comment by Dave2ooo** [comment]
A new version of the ÖBB monitor is available: [OBB Monitor v2](https://github.com/Dave2ooo/oebb-monitor-v2)
